### ISSUE TITLE
Modernize the build and cleanup the repository content 

### ISSUE THREAD

**Issue by merks** [eclipse-datatools/datatools#1]
The  Git repository content has accumulated at lot of unused parts that should be cleaned up.  It should be easier to produce p2 repositories for milestones and releases.  Dependencies should be updated and should be easier to keep up-to-date.   And it should be easier to contribute to the project via an automated setup.

**Comment by merks** [comment]
@sbouchet 

FYI, unless there is something that needs to be fixed before the final release, then the current milestone will remain the current SimRel contribution and I'll promote it to a release.

**Comment by sbouchet** [comment]
ok i'm good with that !
