### ISSUE TITLE
Copy the lpg.lpgjavaruntime package from net.sourceforge.lpg.lpgjavaruntime to org.eclipse.datatools.sqltools.parsers.sql.lexer

### ISSUE THREAD

**Issue by merks** [eclipse-datatools/datatools#13]
I tried to migrate to a newer version of lpg, but that appears to involve regenerating  the lexers/parsers.  In the end, I thought, if it isn't broken, don't fix it.  But the net.sourceforge.lpg.lpgjavaruntime  bundle is really old and I think it came from CVS-based Orbit.   It appears that datatools is the only one using it, at least on SimRel, so I propose to copy the package from here:

![image](https://github.com/eclipse-datatools/datatools/assets/208716/b009cc4b-5e5e-43ac-9b37-62e44f3cfb29)

to here:

![image](https://github.com/eclipse-datatools/datatools/assets/208716/4ffeaad0-19b2-42e3-bd21-6c91af6e6590)

That bundle previous exported the imported bundle but could then export the contained packages:

![image](https://github.com/eclipse-datatools/datatools/assets/208716/f8dc6f7f-e779-4420-bbd0-aa817c8f0153)

@sbouchet  @jeffmaury 

Are you guys okay with that?

**Comment by merks** [comment]
In combination with https://github.com/eclipse-datatools/datatools/pull/12 I could then eliminate all dependencies on older Orbit content and rely purely on what's available in the latest Orbit update sites, i.e., only on this:

https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/milestone/latest

**Comment by sbouchet** [comment]
Looks good to me !

**Comment by merks** [comment]
I opened this iplab issue to record this activity:

https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/11471
