### ISSUE TITLE
Data Tools will not compile against Eclipse 4.31

### ISSUE THREAD

**Issue by brianvfernandes** [eclipse-datatools/datatools#17]
The interfaces org.eclipse.ui.commands.ICommand / ICommandManager / IKeySequenceBinding (and possibly more) have been removed from Eclipse 4.31. Classes using these interfaces like AbstractSQLEditorTextHover will not compile against this release of Eclipse; other code may be affected as well.

According to a note [here](https://github.com/eclipse-platform/eclipse.platform.ui/blob/R4_30_maintenance/bundles/org.eclipse.ui.workbench/Eclipse%20UI/org/eclipse/ui/commands/ICommand.java) we are supposed to use the "org.eclipse.core.commands" plug-in instead.

If it helps, I found [this commit](
https://github.com/eclipse-sourceediting/sourceediting/commit/2ec0321982c9b44d7235fef5a6358741431399c7) in the sourceediting repo where use of this interface was modified to work with 4.31.

**Comment by merks** [comment]
Thank you for reporting the problem.  😀 

It's fixed just in time to be included for the Eclipse 4.31 (SimRel 2024-03) release.

**Comment by brianvfernandes** [comment]
@merks thanks for the lightning fast fix!
