### ISSUE TITLE
Improve error handling for XML parsing errors

### ISSUE THREAD

**Issue by hvbtup** [eclipse-datatools/datatools#24]
The fix #23 for issue #22 does work, but it seems that BIRT does not notice the parsing error and instead it reacts just as if the data set contains no rows.

When a parsing error occurs, then an exception is added to an exception list.
But BIRT seems to not look at this list.

I think that the `org.eclipse.datatools.enablement.oda.xml.util.SaxParserConsumer.next()` method should throw an OdaException if `sp.exceptions` is not empty or something like that?
Or `org.eclipse.birt.report.data.oda.xml.util.SaxParser` should provide it own error handling methods.

The comment at the beginning of `org.xml.sax.ErrorHandler` says "If an application does *not* register an ErrorHandler, XML parsing errors will go unreported. ..."

Unfortunately I am not at all an expert in using Xerces and I know nothing about best practice here.
In the end I think that a SAX parsing error should result in an OdaException.

**Comment by merks** [comment]
Thanks for helping track down the location that needs fixing, for providing a test case to make it easier to focus on the necessary changes, and for testing!

**Comment by merks** [comment]
@hvbtup 

There's a new milestone with the changes:

![image](https://github.com/user-attachments/assets/9e2f72fa-a1e7-4b0a-9cdc-5f6cb503f348)

And I've kicked another BIRT nightly build.
