### ISSUE TITLE
Bad identification for MS SQL Server driver templates

### ISSUE THREAD

**Issue by dhmartin** [eclipse-datatools/datatools#5]
When adding a new definition using SQL Server driver templates, a weird text is shown to identify one of the templates.

Please check commit 7ce7ca5 (June 2018) for comments:
https://github.com/eclipse-datatools/datatools/commit/7ce7ca592b4da651d0062fa3943f9ce8ddc6d30b#commitcomment-123710989

David

**Comment by merks** [comment]
Sorry it took so long....
