### ISSUE TITLE
DALI tools generating the wrong datatype for the column in the entity class when the SQL column datatype is "TEXT"

### ISSUE THREAD

**Issue by lak-proddev** [eclipse-datatools/datatools#6]
The data type is changed to **java.lang.Object** instead of the String for the SQL data type **TEXT.**

Steps To Reproduce:
1. Make sure there is a column with the datatype **TEXT**  in the database.
2. Try to generate the entities from the existing tables.
3. The first time the column in the entity is generated with the **String** data type.
4. If we try a second time, the column generates with the **java.lang.Object**.

Sample SQL script

CREATE TABLE database_test (
id int NOT NULL AUTO_INCREMENT,
name varchar(45) DEFAULT NULL,
address text,
PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='None';

**Comment by merks** [comment]
I think you are using tools form this project aren't you?

https://projects.eclipse.org/projects/webtools.dali/developer

**Comment by merks** [comment]
I'm going to assume this is a  Dali project issue and not a data tools issue.

**Comment by lak-proddev** [comment]
It's a Datatools issue, I going to provide a fix for it

**Comment by merks** [comment]
I see.

**Comment by merks** [comment]
The fix is in a nightly build:

https://download.eclipse.org/datatools/updates/nightly/latest

Thank you for contributing!

**Comment by lak-proddev** [comment]
> The fix is in a nightly build:
> 
> https://download.eclipse.org/datatools/updates/nightly/latest
> 
> Thank you for contributing!



> The fix is in a nightly build:
> 
> https://download.eclipse.org/datatools/updates/nightly/latest
> 
> Thank you for contributing!

No problem.
I  need some time to write a test case. Since busy with other priorities,
